### ISSUE TITLE
Add Exposed=Worker,Window to Extension to Performance interface

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/user-timing#10]
See https://github.com/w3c/navigation-timing/issues/22

**Comment by igrigorik** [comment]
@toddreifsteck based on https://github.com/w3c/navigation-timing/issues/22#issuecomment-121973465, I doesn't look like this is necessary?

**Comment by toddreifsteck** [comment]
100% agreed! Learning something about WebIDL every day.
