### ISSUE TITLE
"from navigationStart to the current time" is incorrect

### ISSUE THREAD

**Issue by plehegar** [w3c/user-timing#11]
Worker support needs more work despite #8 and #10.

Working on a PR to fix that and revamp user timing while I'm at it.

For example, we need something along:
[[
All global object have a mark list. Unless the mark is invoked, its mark list is empty. Each member of the list is a pair formed by a markName and a recorded time, respectively a DOMString and a DOMHighResTimeStamp. 

The mark(markName) method MUST run these steps:

    Let recorded time be the time in milliseconds from the time origin to the occurrence of the call to the mark method.
    If markName uses the same name as an attribute in the PerformanceTiming interface [navigation-timing-2], throw a SyntaxError.
    Let pair be the pair markName and recorded time.
    Add pair to mark list.
    Return undefined.

[and so on]
]]

**Comment by plehegar** [comment]
(I'm blocking on #1 )

**Comment by igrigorik** [comment]
Why does this block on #1? Isn't the switch to use "time origin" is something we need to do regardless?

**Comment by plehegar** [comment]
Because I was refactoring the spec when I realized it. If #1 gets too long to resolve, I'll do a separate patch.

**Comment by plehegar** [comment]
See https://github.com/w3c/user-timing/pull/13

**Comment by plehegar** [comment]
I believe this one is fixed. We're now using "the value that would be returned by the Performance object's now() method." ok to close?

**Comment by igrigorik** [comment]
lgtm, closing!
