### ISSUE TITLE
Handling repeat metrics and measures + custom startTime?

### ISSUE THREAD

**Issue by igrigorik** [w3c/user-timing#14]
From: https://lists.w3.org/Archives/Public/public-web-perf/2015Nov/0008.html

---

So I've been using the user timing api for a bit and I'm slowly starting to
think that the current API might not be optimal.

Here is my use case:
I have one async function that starts a cascade of other async functions,
and each of those functions can also start more functions. To "start" a new
function, all of my functions use a utility method.

I've rigged this utility method so that it will time each of the async
functions and log with the User Timing API. However, the current API
requires a unique string to be provided when recording "marks" and those
strings are needed again to record a "measure." Right now I'm using the
function names as the unique string but since these functions can be
executed multiple times asynchronously, the measures are incorrect.

I want to propose an API where a call to `performance.mark()` returns a
unique javascript object, lets call it a marker. And when I call
`performance.measure()` I should be able to pass to it two markers and have
it record the time between the markers.

Right now, my workaround is to build a wrapper around `performance.mark`
and `performance.measure` to provide the API I suggested above, while
handling name collisions and using the current API under the hood. It is
turning out to be more work than I'd like.

I have no idea how far along the User Timing Spec is but does this sound 
reasonable to consider?

---

Followup:
- https://lists.w3.org/Archives/Public/public-web-perf/2015Nov/0011.html
- https://lists.w3.org/Archives/Public/public-web-perf/2015Nov/0012.html

**Comment by natduca** [comment]
@lpy how well would this work for our use cases?

**Comment by jakub-g** [comment]
> I want to propose an API where a call to performance.mark() returns a
unique javascript object, lets call it a marker. And when I call
performance.measure() I should be able to pass to it two markers and have
it record the time between the markers.

Looks like this will be solved by https://github.com/w3c/user-timing/issues/23#issuecomment-331966311 (`performance.mark` returning and `performance.measure` accepting `PerformanceEntry`)

**Comment by npm1** [comment]
The current shape of UserTiming L3 allows passing in a timestamp. This allows more use cases than passing in a `PerformanceEntry`, and if you want to use such entry you can pass in `entry.startTime`
