### ISSUE TITLE
Transition Level 2 to CR

### ISSUE THREAD

**Issue by igrigorik** [w3c/user-timing#19]
- [x] **Known / outstanding spec issues**
  - [x] document [updates from L1](https://www.w3.org/2016/06/WebPerfWGroadmap.html)
- [x] **Web platform tests**
  - https://github.com/w3c/web-platform-tests/tree/master/user-timing
  - [x] Worker Tests for User Timing: https://github.com/w3c/user-timing/issues/20
- [x] **Privacy and security**
  - https://w3c.github.io/user-timing/#privacy-security
  - [x] update to refer to HR-Time L2 
- [x] **Implementations**
  - Chrome: [M46+](https://crbug.com/465643)
  - Firefox: [M41](https://developer.mozilla.org/en-US/Firefox/Releases/41)
  - Edge: [IE10+](https://blogs.msdn.microsoft.com/ie/2013/02/26/ie10-for-windows-7-globally-available-for-consumers-and-businesses/); Worker support is Edge 15+(TBD).
  - Safari: no public signals

**Comment by igrigorik** [comment]
@toddreifsteck @plehegar ptal at the above commits. I believe the doc itself should be ready to go for L2 CR. The main outstanding item is the Worker test coverage.

**Comment by igrigorik** [comment]
Approved CR transition: https://www.w3.org/2016/10/26-webperf-minutes.html

**Comment by plehegar** [comment]
Actually, we never published a FPWD of that draft. I'll request one right away and will move to CR within a 2/3 weeks after wide review. ok?

**Comment by igrigorik** [comment]
Sounds good.

**Comment by toddreifsteck** [comment]
Agreed! Lets get the draft published.

**Comment by toddreifsteck** [comment]
Neither IE nor Edge < 15 support User Timing on Workers because we do not yet support Performance Timeline on Workers. Edge 15 is still TBD.

**Comment by igrigorik** [comment]
@toddreifsteck thanks, updated the summary above.

**Comment by plehegar** [comment]
UT2 got published as a FPWD today

**Comment by igrigorik** [comment]
Thanks @plehegar! For future reference, ML threads: 
- [Wide Review for User Timing 2](https://lists.w3.org/Archives/Public/public-web-perf/2016Nov/0003.html)
- [Call for Exclusions: User Timing Level 2](https://lists.w3.org/Archives/Public/public-web-perf/2016Nov/0001.html) - ending on 31 March 2017 23:59 UTC.

**Comment by plehegar** [comment]
We'll publish Level 2 as CR in early January, waiting for the patent policy clock to run out.

**Comment by igrigorik** [comment]
Per last call: resolved to push L2 to CR. Closing.

**Comment by igrigorik** [comment]
For reference, CR live @ https://www.w3.org/TR/2018/CR-user-timing-2-20180709/
