### ISSUE TITLE
negative duration values

### ISSUE THREAD

**Issue by plehegar** [w3c/user-timing#2]
From https://lists.w3.org/Archives/Public/public-web-perf/2015Jan/0049.html
[[
In working on the implementation of the User Timing spec in Gecko, it was
brought up about the potential of durations to return negative values.
Specifically it was unclear from the spec whether things like this should
be allowed:

```js
performance.mark('A');
performance.mark('B');

performance.measure('delta', 'B', 'A');

assert( performance.getEntriesByName('delta')[0].duration < 0 ); // true
```

Chrome allows this interaction, enabling negative duration values for
measures. Is this intended, and if so, should we clarify the spec that
negative durations are allowed for performance measurements specifically?
]]

**Comment by igrigorik** [comment]
I think negative values are reasonable, and AFAIK, IE allows negative values as well.

**Comment by toddreifsteck** [comment]
Ilya is correct. A quick test during the call when we discussed this issue demonstrated that many browsers allow negatives. I believe we should update the spec with this language.

**Comment by toddreifsteck** [comment]
@phlegar Please let us know if you have feedback on the merged update. Thanks!
