### ISSUE TITLE
Worker tests for User Timing

### ISSUE THREAD

**Issue by igrigorik** [w3c/user-timing#20]
We're missing tests for integration with Worker:
https://github.com/w3c/web-platform-tests/tree/master/user-timing

**Comment by toddreifsteck** [comment]
I have some new tests on this.... I can submit, but it seems like Firefox/Chrome should have done this already. (Ok.. done soapboxing now. :-))

**Comment by JosephPecoraro** [comment]
@toddreifsteck did you submit your tests?

**Comment by igrigorik** [comment]
I don't see anything in [wpt commit history](https://github.com/w3c/web-platform-tests/commits/master/user-timing). @toddreifsteck is this something you're still willing to upstream? :)

**Comment by JosephPecoraro** [comment]
It looks like this was handled by https://github.com/w3c/web-platform-tests/pull/5247? All of the tests appear to be `*.any.js` so they should run in a worker, right? @plehegar did a great job with the cleanup.

**Comment by igrigorik** [comment]
Doh, I missed that! You're right, @plehegar's commit covers all the bases we're looking for -- thanks Philippe!  Great catch Joseph. 

Closing this.
