### ISSUE TITLE
measure() may throw SyntaxError

### ISSUE THREAD

**Issue by plehegar** [w3c/user-timing#21]
See
 https://w3c-test.org/user-timing/test_user_timing_measure_exceptions.html
and User Timing L1

**Comment by JosephPecoraro** [comment]
I assume this is covering the case where no mark is found but startMark/endMark was present?

**Comment by philipwalton** [comment]
@plehegar I'm getting a 404 when visiting that link.

Can you clarify whether you're referring to the case @JosephPecoraro mentioned? And are you suggesting the spec needs to be updated to reflect this for Level 2?

**Comment by igrigorik** [comment]
@philipwalton I believe you're looking for: https://w3c-test.org/user-timing/measure_exceptions_navigation_timing.html; see https://w3c-test.org/user-timing/ for full list.

**Comment by plehegar** [comment]
there is also https://w3c-test.org/user-timing/measure_syntax_err.any.html

**Comment by philipwalton** [comment]
@igrigorik out of curiosity, do you remember why this throws a SyntaxError? Since marks and measures have different entry types from navigation entries, it seems like maybe this is an unnecessary restriction?

**Comment by philipwalton** [comment]
Note, from the January 18, 2018 call we resolved to NOT throw in some cases that we currently expect to throw in Web Platform Tests. This is tracked in #36.
