### ISSUE TITLE
What does "navigationStart" mean as a second argument to performance.measure() in a web worker?

### ISSUE THREAD

**Issue by plehegar** [w3c/user-timing#22]
See
   https://lists.w3.org/Archives/Public/public-web-perf/2016Dec/0007.html

**Comment by igrigorik** [comment]
Related discussions: https://github.com/w3c/user-timing/issues/1, https://github.com/w3c/user-timing/pull/18/files.

> My hunch is that the whole exception business is not something we would do if we were writing the spec today, but for historical reasons I think we need to maintain this behavior; let's freeze the list of attributes on NT1 and move on.

Is the "historical reasons" bit actually true? It would make everyone's life a lot easier, and a lot less confusing, if we dropped this requirement entirely from L2. Consider...

```
performance.mark('foo')
performance.measure('bar', 'loadEventStart', 'foo')
```

The hand-wavy explanation is: look for a mark whose name matches "loadEventstart", or if the name is an attribute name of PerformanceTiming then use that value. However...
- 'that value' is a different type (unsigned long long; not a DOMHighResTimestamp), and doesn't have a defined time origin / uses epoch time.
- we are then performing math against foo's startTime, which is a DOMHighResTimestamp.

All of this seems completely unnecessary and confusing. My proposal is that we drop the whole PerformanceTiming business entirely in UT. The only reason to raise an exception is if the start or end name doesn't find a matching mark in the performance buffer.

WDYT? /cc @toddreifsteck @bzbarsky

**Comment by nicjansma** [comment]
@igrigorik Do we have an usage stats on `measure` 2nd/3rd arguments referring to PerformanceTiming entries?

I've seen examples and explanations in the past using `responseStart` or `loadEventStart/End` for `startMark`.

**Comment by toddreifsteck** [comment]
@igrigorik I believe User Timing assumed the existence of Navigation Timing 2 when it was created. If you look at it through that lens (aka.. how IE11/Microsoft Edge implemented it) then it "makes sense". I've seen some usage of this but don't have stats on how often it is used (nor can I figure this out in the next ~3 months).

**Comment by igrigorik** [comment]
@toddreifsteck ah, that's a good point. So now we're in a pickle...

- In #1 we identified that this whole thing is a mess and we don't want to carry it forward; we bound these names to PerformanceTiming interface. However, the values on that interface are epoch times. Doh.
- Instead, if we assume that all of this is supposed to be backed by NT2.. we fix the problem with values. However, this then opens up the earlier can of worms: we have attributes on NT2 that don't make sense for `measure()` and we're propagating this entire mess into NT2...
  - Further, the above assumes that there is only _one_ NT entry. One of our goals for NT/RT L3's is to unpack redirects and other fetches, which means that it's perfectly reasonable to have multiple NT entries -- that will break current NT2 logic. In other words, rebasing support for these names onto NT2 will only kick the same problem down the road to NT3.

AFAIK, we don't have telemetry in Chrome for use of these parameters... I guess one thing we could try, as a first order approximation, is to scan HTTP Archive payloads and see if we can find any usage.

**Comment by bzbarsky** [comment]
@igrigorik I haven't really been following this stuff enough to have strong opinions on how it should work, sorry.

**Comment by JosephPecoraro** [comment]
At some point between UT1 and UT2 `measure()` was changed to only look for `PerformanceMark` instances in the buffer (https://github.com/w3c/user-timing/commit/5d1e83e227a58c20d0db31682860a9bed3b2af53).

> 2. If endMark is omitted, let end time be the value that would be returned by the Performance object's now() method. Otherwise let end time be the value of the startTime attribute from the most recent occurence [sic] _PerformanceMark_ object in the performance entry buffer whose name matches value endMark.
>
> 3. If startMark is omitted, let start time be 0. Otherwise let start time be the value of the startTime attribute from the most recent occurence [sic] _PerformanceMark_ object in the performance entry buffer whose name matches value startMark.

That would seem to eliminate the special names consideration already. But it sounds like comments about are discussing bringing it back to support existing implementations?

So let me try and get the lay of the land.

---

What would you like to see in order to measure the time between the original "loadEventStart" and "now"?

1. Using measure with special names? (Sounds like we want this to go away)

```js
performance.measure("x", "loadEventStart");
let measures = performance.getEntriesByType("measure");
let measure = measures[measures.length - 1];
let desired = measure.duration;
```

2. Using performance.timing? (Sounds like this is going away)

```js
let now = performance.now();
let desired = now - (performance.timing.loadEventStart - performance.timeOrigin)
```

3. Using global entries list? (Compatible with multiple Navigation Entries)

```js
let now = performance.now();
let navigation = performance.getEntriesByType("navigation")[0];
let desired = now - navigation.loadEventStart;
```

4. Using PerformanceObserver? (Value not needed immediately)

```js
performance.mark("x");
let po = new PerformanceObserver((list) => {
    let firstNavigation = performance.getEntriesByType("navigation")[0];
    for (let mark of list.getEntriesByName("x")) {
        let desired = mark.startTime - firstNavigation.loadEventStart;
    }
});
po.observe({entryTypes:["mark"]});
```

5. Using only PerformanceObserver?! (Gross way to look up Navigation Entries)

```js
performance.mark("x");

let firstNavigation = null;
let po = new PerformanceObserver((list) => {
    if (!firstNavigation) {
        firstNavigation = list.getEntriesByType("navigation")[0];
        po.observe({entryTypes:["mark"]);
    }
    for (let mark of list.getEntriesByName("x")) {
        let desired = mark.startTime - firstNavigation.loadEventStart;
    }
});
po.observe({entryTypes:["navigation", "mark"], buffered:true});
```

6. Something else? New API / proposal?

---

Looking at 3-5 above, it seems we don't need `measure()` to determine times from Navigation Timing timestamps if we can look up the PerformanceNavigationTiming entries.

So, circling back to the original issue: In Window and Workers, we don't need the headache at all. If `measure()` is made to only work with marks, then we can have no special name handling in workers. All we should do is clarify the error cases for measure given startMark/endMark are provided but not found. If we need to support something for backwards compatibility it seems like it can be specific to Window, like the existing mark SyntaxError is.

**Comment by philipwalton** [comment]
Can we get a resolution on this issue?

I agree with @igrigorik's suggestion here:

> All of this seems completely unnecessary and confusing. My proposal is that we drop the whole PerformanceTiming business entirely in UT. The only reason to raise an exception is if the start or end name doesn't find a matching mark in the performance buffer.

 I think using strings to identify all these reference points -- a list that's likely to keep getting bigger -- is not very manageable going forward.

That being said, I do think there's a lot of value in being able to create measurements using reference points that author code may not have access to (or been around for), and this could be solved by allowing `.measure()` to accept `PerformanceEntry` objects as proposed in #23.

Some use cases that come to mind:

* Measuring the time between any number of RT points prior to when script can run and some action in the script.
* Measuring service worker response or startup time (via either common names between document-code and SW-code, or some future SW PerformanceEntry types).

I'm in favor of updating `.measure()`'s `startMark` and `endMark` definition to be either a `DOMString` or a `PerformanceEntry`. If it's a `DOMString` it's assumed to be a mark name, and we can add a note that for historical reasons some implementation accept the names of RT entries but unknown names will throw.

**Comment by igrigorik** [comment]
@philipwalton @JosephPecoraro would you be able to dial in for next WG call (25th @ 10AM PST) to discuss this? I'm hoping a higher bandwidth channel can help us drive this one to a conclusion. Added this to the [agenda](https://docs.google.com/document/d/10dz_7QM5XCNsGeI63R864lF9gFqlqQD37B4q8Q46LMM/edit#heading=h.kplnsudwiv74), lmk.

**Comment by JosephPecoraro** [comment]
> All of this seems completely unnecessary and confusing. My proposal is that we drop the whole PerformanceTiming business entirely in UT. The only reason to raise an exception is if the start or end name doesn't find a matching mark in the performance buffer.

I agree. Using special names at all is weird. I'm in favor of dropping it.

> I'm in favor of updating .measure()'s startMark and endMark definition to be either a DOMString or a PerformanceEntry. If it's a DOMString it's assumed to be a mark name, and we can add a note that for historical reasons some implementation accept the names of RT entries but unknown names will throw.

I agree. Strings as markers leads to ambiguity (first marker with that name, or last marker with that name?). Using explicit PerformanceEntry objects themselves is clear and straightforward.

**Comment by philipwalton** [comment]
On the call [25 Sep call](https://www.w3.org/2017/09/25-webperf-minutes.html) I believe we decided to not support NT names going forward, so I think this issue can be closed?

**Comment by toddreifsteck** [comment]
My recollection from the call is that we want to freeze the current list of strings and that a UA will gather Telemetry to figure out whether we can deprecate.

**Comment by philipwalton** [comment]
Ahh, yes, you're right. We had that on our todo list; I'll see if we did it.

Also, when I wrote what I wrote above, I was under the impression that the use of NT names in `measure()` calls was unspecified behavior that all implementations happened to agree upon. Now I'm seeing that it's not mentioned in the L2 spec, but [it is mentioned in L1](https://www.w3.org/TR/user-timing/#dom-performance-measure) (though it doesn't mention how to treat the differing start times):

> May be the name of one of the attributes in the PerformanceTiming interface [Navigation Timing]. In this case, the value of that attribute is used as the start DOMHighResTimeStamp time value.

**Comment by philipwalton** [comment]
Following up a bit here from our discussion on that last call. Here's what I found when testing the use of NT names in `measure()` calls inside a worker:

- All browsers except Edge throw when an NT name is used
- Omitting the 2nd arg (which is supposed to default to `navigationStart`) does not throw in any browser.

@tdresser is going to `measure()` usage with both explicit NT names as well as implicit NT names (by omitting the 2nd arg).

If usage is low, my preference would be to disallow NT names in workers by specifying that we throw whenever an NT name is used (explicitly or implicitly).

If it's common for `measure()` calls in a worker to omit the 2nd argument (and we can't throw), I propose we spec it as defaulting to the value of `performance.timeOrigin` to avoid any dependance on NT names.

**Comment by tdresser** [comment]
@npm1 is probably going to do the leg work here.

**Comment by philipwalton** [comment]
> Omitting the 2nd arg (which is supposed to default to navigationStart) does not throw in any browser.

Actually, it looks like defaulting to `navigationStart` was [level 1 behavior](https://www.w3.org/TR/user-timing-2/#dom-performance-measure), but [level 2 defaults to 0](https://www.w3.org/TR/user-timing/#dom-performance-measure), so I don't think we need to investigate the worker case further if everyone is fine with throwing a `SyntaxError` if an NT name is used in a worker.

**Comment by igrigorik** [comment]
Resolved via https://github.com/w3c/user-timing/pull/35.
