### ISSUE TITLE
measure() may throw InvalidAccessError

### ISSUE THREAD

**Issue by plehegar** [w3c/user-timing#26]
window.performance.measure() method throws a InvalidAccessError whenever a navigation timing attribute with a value of zero is provided as the startMark or endMark.
See also
 https://github.com/w3c/user-timing/issues/22
 https://w3c-test.org/user-timing/test_user_timing_measure_exceptions.html

**Comment by philipwalton** [comment]
Similar question to #21, did these links move?

**Comment by plehegar** [comment]
it's now at https://w3c-test.org/user-timing/measure_exceptions_navigation_timing.html

**Comment by philipwalton** [comment]
Oh the call [25 Sep call](https://www.w3.org/2017/09/25-webperf-minutes.html) I believe we decided to not support these going forward, and add a note that, for compatibility reasons, implementations are encouraged to support the list of names from the [Navigation Timing L2 spec](https://www.w3.org/TR/navigation-timing-2/).

Are folks OK with leaving this unspec'ed, or should we specifically spec what's supported and note that we will not be expanding the list in the future?

**Comment by igrigorik** [comment]
Unfortunately we can't drop NT names, as we don't know what impact it will have. 

In terms of next steps, I believe we agreed on the following:
- Explicitly enumerate and freeze the list of "special" names in UT spec, to make it explicit which names should result in an error. 
   - Add a reference to Navigation Timing L1 and point to `PerformanceTiming` as the source of these names with a note that we do not intend to support any new attributes from L2 or beyond.
- Update processing algorithms for measure and mark to use list defined above. 

Separately, we'd like to get telemetry from one of the browsers on how often these names are used in the wild. If/when this fraction falls below our acceptable threshold, we can deprecate this functionality.

@toddreifsteck does that match your thinking?

**Comment by igrigorik** [comment]
Resolved via https://github.com/w3c/user-timing/pull/35.
