### ISSUE TITLE
Existing Test gap: Verify that toJSON output is created properly

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/user-timing#29]
The WebIDL test verifies the existence of the method, but we've seen that sometimes properties are not serialized properly historically. We need a test for this.

**Comment by plehegar** [comment]
Note that https://github.com/w3c/web-platform-tests/pull/7490 doesn't trigger the toJSON check.
@tobie, should we add toJSON to the PerformanceMark and PerformanceMeasure definitions as well?

**Comment by tobie** [comment]
Well, you're not creating a `PerformanceEntry` object, so it can't test.

**Comment by plehegar** [comment]
ok. I moved the PerformanceEntry definition into the to-test section. It does work, it it now triggers the test of toJSON but it generates two test name "Test default toJSON operation of PerformanceEntry" since I'm testing on both mark and measure...

**Comment by tobie** [comment]
That is weird. Mind filing that too?

**Comment by plehegar** [comment]
@tobie, see https://github.com/w3c/web-platform-tests/issues/7492

**Comment by igrigorik** [comment]
@plehegar @tobie any updates on this?

**Comment by tobie** [comment]
I was hoping to get a sponsor for the work required to keep idlharness up to date. Unfortunately, that didn't work out. So I don't have an ETA on a fix.

**Comment by igrigorik** [comment]
@plehegar does w3c/web-platform-tests#7492 block us landing tests, or can we do a workaround? We'd like to get this unblocked.

**Comment by npm1** [comment]
This issue can be closed.
https://github.com/w3c/web-platform-tests/pull/11056

**Comment by igrigorik** [comment]
👍 thanks Nicolas!
