### ISSUE TITLE
Clarify what Navigation Timing entries are allowed and how to use their values

### ISSUE THREAD

**Issue by philipwalton** [w3c/user-timing#31]
The current editor's draft doesn't mention that Navigation Timing entries are allowed in `measure()` calls. The published spec does mention this, but it don't specify how to translate epoch time values to values relative to [`performance.timeOrigin`](https://www.w3.org/TR/hr-time/#dom-performance-timeorigin).

**Comment by igrigorik** [comment]
Resolved via https://github.com/w3c/user-timing/pull/35.
