### ISSUE TITLE
Fix respec warnings and processing

### ISSUE THREAD

**Issue by igrigorik** [w3c/user-timing#32]
The spec doesn't render correctly and throws respec warnings:

![image](https://user-images.githubusercontent.com/10652/32418725-d1de3e9c-c223-11e7-9f72-daf82d35ba1a.png)

Preview: https://w3c.github.io/user-timing/

**Comment by tdresser** [comment]
Philip, I'm happy to take this if you want.

**Comment by philipwalton** [comment]
@tdresser if you have time go ahead. Unfortunately I have jury duty this week, so I don't know when I'll be able to get to it.

**Comment by marcoscaceres** [comment]
This is fixed, so closing
