### ISSUE TITLE
Update WP tests to not throw when NT1 names are used as the first arg in measure calls

### ISSUE THREAD

**Issue by philipwalton** [w3c/user-timing#36]
In the January 18, 2018 call, we discussed the implementation differences for this issue. Currently Firefox throws but none of the other browsers do.

We resolved to NOT throw in `measure()` calls when the measure name (1st argument) is the same as an NT1 name. Our reasoning:

- There was concern that since Chrome and Safari don't throw today, sites that target mobile may be at risk of breaking if we update to throw.
- `mark()` throws when using NT1 names because it creates ambiguity in `measure()` calls, since they can refer to either mark or NT1 names. There is no similar ambiguity in the `measure()` case.

This resolution will require a change to Web Platform Tests. We also need to ensure that #35 is updated to make this behavior explicit.

**Comment by philipwalton** [comment]
#35 updates the spec text for this. We still need to make sure the Web Platform Tests are updated as well.

**Comment by igrigorik** [comment]
I'd really like to get someone from Mozilla to review and sanity check this. @marcoscaceres could you help identify the right person on your side?

@philipwalton do you have cycles to update the WPT test for this?

**Comment by philipwalton** [comment]
Yeah, I can update the tests once we agree this is the right direction.

**Comment by marcoscaceres** [comment]
Trying to find someone someone on the Mozilla side...

**Comment by bakulf** [comment]
I can help here. I have done mostly of the DOM side of the Performance API in firefox.
I'll file a bug and I'll work on it asap.

**Comment by bakulf** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1444150

**Comment by philipwalton** [comment]
Great! @bakulf it sounds like you're saying Mozilla is fine with the resolution to not throw. Correct?

In that case we can update the Web Platform Tests and proceed with moving the spec to CR.

**Comment by bakulf** [comment]
Yes, measure(name) doesn't throw any more on firefox if the name matches one of the readonly attribute of Performance interface.

https://hg.mozilla.org/integration/mozilla-inbound/rev/2e0412dd3fc90ac56d86f2c1846f004d3477e22b

In this push I updated the WPT too.

**Comment by igrigorik** [comment]
@bakulf we don't see the tests propagated to https://github.com/w3c/web-platform-tests/tree/master/user-timing, is there an extra step?

**Comment by bzbarsky** [comment]
PRs against wpt should be getting created automatically when changesl like that land, I thought.  @jgraham ?

**Comment by nolanlawson** [comment]
I just manually tested the new Mozilla web-platform-tests from that Mozilla bug, and EdgeHTML 16 passes all the tests in `invoke_with_timing_attributes.html` and `measure_exceptions_navigation_timing.html`. This indicates that Mozilla now agrees with the spec, so this issue can be closed.

**Comment by jgraham** [comment]
The Gecko sync process got very upset for slightly involved reasons when some commits it landed were backed out. The upstreaming part thought that backout was something it could upstream, and ended up erroring out. I have a fix in progress and the service will catch up when that lands.
