### ISSUE TITLE
Update the introductory text to explain how this API differs from performance.now()

### ISSUE THREAD

**Issue by philipwalton** [w3c/user-timing#37]
Comment from @nolanlawson in #35

> It may be worthwhile to mention here the benefits of mark()/measure() relative to performance.now(). Without mentioning performance.now(), Date.now() might seem like a straw man.

> Perhaps mentioning Dev Tools support or support in tools like Windows Performance Analyzer and WebPageTest may be worth putting in a non-normative section. Not sure if it's out-of-scope for this document though.

I agree, it's not clear how the use cases for UT differ from `performance.now()`; it's probably worth explaining that.

**Comment by toddreifsteck** [comment]
@plehegar @tobie Can the PR for adding these tests be completed? How do we push on the blocking issue?

**Comment by tobie** [comment]
Sorry, @toddreifsteck, I don't understand your comment in relation to the context.

**Comment by philipwalton** [comment]
I believe @toddreifsteck's comment was actually in reference to #29.

**Comment by tobie** [comment]
Oh, OK. So I answered this there already: https://github.com/w3c/user-timing/issues/29#issuecomment-367800886. Sorry it's not good news. :(

**Comment by igrigorik** [comment]
A bit of a tangent, but since we're talking about intro text.. We also need to update the intro to explain what's new in L3 and ideally provide some examples of new capabilities. 

/cc @philipwalton @npm1

**Comment by yoavweiss** [comment]
This was covered by #77. Closing, but feel free to reopen if e.g. you feel that tackling this question in the README is not sufficient.
