### ISSUE TITLE
Publish L2 CR and snapshot in v2 branch

### ISSUE THREAD

**Issue by igrigorik** [w3c/user-timing#41]
All outstanding L2 issues are resolved and we approved L2 CR on last call. 

@siusin could you help us publish the L2 CR?

**Comment by siusin** [comment]
TransReq sent :)

For the record,
Wide review request: https://lists.w3.org/Archives/Public/public-review-announce/2016Nov/0004.html
Implementation Status: https://wpt.fyi/results/user-timing

**Comment by igrigorik** [comment]
Thank you!
