### ISSUE TITLE
Level 3 proposal

### ISSUE THREAD

**Issue by philipwalton** [w3c/user-timing#43]
At TPAC last year we discussed (and I believe reached consensus on) a set changes for level 3 of this spec.

@tdresser outlined the current L3 proposal in [this doc](https://docs.google.com/document/d/1hltt8z9C4PaI5Qu1YMIp1wOGdbJPJPoJwBarEeCY6xQ/edit?usp=sharing
). If anyone has additional feedback on this proposal, please comment here or in the doc.

**Comment by toddreifsteck** [comment]
@tdresser @philipwalton @wanderview My observation is that User Timing 3 is a simple iteration from User Timing 2 that should be easy to lock down (other than bike shedding) and should add key primitives allowing https://github.com/wanderview/fetchevent-worker-timing to be very simple. Would love to see this proposal design driven to completion!

**Comment by npm1** [comment]
Per the discussion at our last call, now that https://github.com/w3c/user-timing/pull/52 has been merged, we are good to go with publishing a 'draft' version of level 3. @yoavweiss @toddreifsteck could you do this, ask someone who can do this to do it, or tell me how to do this? :) Thanks!

**Comment by npm1** [comment]
I think @siusin published draft version, so closing this. Thanks!
