### ISSUE TITLE
Measure API: make startOrOptions nullable

### ISSUE THREAD

**Issue by maxlgu** [w3c/user-timing#48]
This is the current API:
PerformanceMeasure measure(DOMString measureName, optional (DOMString or PerformanceMeasureOptions) startOrMeasureOptions, optional DOMString endMark);

In the API, startOrMeasureOptions is not nullable. When users run measure("name", null, "mark"), startOrMeasureOptions will be interpreted as {}.

Making startOrMeasureOptions both optional and nullable will solve the problem.

**Comment by npm1** [comment]
Can you explain why we would want to support measure("name", null, "mark")? In particular, how is this any different from void measure(DOMString measureName, optional DOMString startMark, optional DOMString endMark)? Here, the DOMStrings are not nullable.

**Comment by maxlgu** [comment]
Also, these cases are indistinguishable as well, because PerformanceMeasureOptions only support startTime, endTime and detail as its attributes.

measure("name", {}, "mark")
measure("name", {start: 123}, "mark") // Note that I use start not startTime. start is not a legal attribute in PerformanceMeasureOptions but it's ignored silently.

**Comment by npm1** [comment]
As an update, from https://heycam.github.io/webidl/#es-union it looks like null or undefined are converted to the empty dictionary. So we need to either make the parameter nullable so that that doesn't happen, or special case the empty dictionary to treat it as if the parameter was not there. Any thoughts on what would be better in this case @yoavweiss @igrigorik?

**Comment by npm1** [comment]
There was a suggestion to use two methods instead of one in order to make the IDL simpler. From a web developer perspective, would it be clearer to have a single mark and measure as is currently [spec'd](https://w3c.github.io/user-timing/#extensions-performance-interface) or would something like this be preferable? @nicjansma @cvazac would love your opinion on this :)

```
PerformanceMark mark(DOMString markName);
PerformanceMark markWithOptions(DOMString markName, PerformanceMarkOptions markOptions);
PerformanceMeasure measure(DOMString measureName, optional DOMString startMark, optional DOMString endMark);
PerformanceMeasure measureWithOptions(DOMString measureName, PerformanceMeasureOptions measureOptions);
```

**Comment by npm1** [comment]
Hm true, mark is simpler so doesn't really need an extra method. So I think we could go with:

`
PerformanceMark mark(DOMString markName, PerformanceMarkOptions markOptions);
PerformanceMeasure measure(DOMString measureName, optional DOMString startMark, optional DOMString endMark);
PerformanceMeasure measureWithOptions(DOMString measureName, PerformanceMeasureOptions measureOptions);
`

@tdresser FYI

**Comment by tdresser** [comment]
Works for me!

**Comment by npm1** [comment]
Reopening this issue based on the discussion at the call today. The AI from the call was to set up a poll to decide whether developers would prefer only having measure()  vs measureWithOptions(). Basically the difference is that in the first option the second parameter is overloaded as either the start or the dictionary, whereas in the second there is a new method for calling the API with the dictionary.

Option 1: having only measure. The API would look like this:

````
PerformanceMeasure measure(DOMString measureName, optional (DOMString or PerformanceMeasureOptions)? startOrMeasureOptions, optional DOMString endMark);
````

Option 2: having measureWithOptions. The API would look like this:
````
PerformanceMeasure measure(DOMString measureName, optional DOMString startMark, optional DOMString endMark);
PerformanceMeasure measureWithOptions(DOMString measureName, PerformanceMeasureOptions measureOptions);
````

**Comment by cvazac** [comment]
I'm not against switching this, but here's the pathological example I was trying to get to in the call, just for fun:

A library that wraps the `measure()` method could not with 100% certainty know the name of the starting mark. If the library caught the following:

```
performance.measure("the name", {
  "startTime": "startMark"
  "toString": () => "otherMark"
}, "the end name")
```

For the name of the starting mark:
- Browsers that support the dictionary would use `"startMark"`.
- Older browsers that don't support the dictionary would use `"otherMark"`.

And I _think_ that a library could only feature detect by calling `measure()` and trapping `toString()` or a getter.

Probably nothing that we need to worry about. 😄

**Comment by npm1** [comment]
True, you'd need to detect L2 vs L3 before that call to measure. One way to do it would be to do a dummy mark() or measure() and just check if there is a return value. Another way to do it is to try to create a new PerformanceMark and check if you get an exception.

**Comment by cvazac** [comment]
> True, you'd need to detect L2 vs L3 before that call to measure. One way to do it would be to do a dummy mark() or measure() and just check if there is a return value. Another way to do it is to try to create a new PerformanceMark and check if you get an exception.

Presuming that all of those features land at the same time in every browser, I agree with you. 😄

**Comment by philipwalton** [comment]
The best way to feature detect this is probably to check for the presence of `detail` in the prototype, otherwise you'd add a measure to the timeline (which you probably don't want to do):

```js
if ('detail' in PerformanceMeasure.prototype) {
  // Assume L3 here...
}
```

**Comment by npm1** [comment]
We did a twitter [poll](https://twitter.com/yoavweiss/status/1103777205958688768) to ask developers what would be more ergonomic and a single measure() method was the clear winner. Based on this and the WebPerf call discussion, we're sticking with this.
