### ISSUE TITLE
Better Recommended Mark Names?

### ISSUE THREAD

**Issue by plehegar** [w3c/user-timing#5]
From thread at
 https://lists.w3.org/Archives/Public/public-web-perf/2015Jun/0102.html

[[
performance.mark('navigationLoaded');
Emit this marker when your application designates that its core chrome or navigation interface exists in the DOM and you have marked it as ready to be displayed, e.g. when the element is not display: none; or other hiding functionality.

performance.mark('navigationInteractive');
Emit this marker when your application designates that the core chrome or navigation interface has its events bound and is ready for user interation.

performance.mark('visuallyLoaded');
This marker maps to the important Content Visible marker above. Emit this when your application designates that it is visually loaded, e.g. the "above-the-fold" content exists in the DOM and you have marked it as ready to be display, again not display: none; or other hiding functionality.

performance.mark('contentInteractive');
Emit this marker when your application designates that it has bound the events for the minimum set of functionality to allow the user to interact with the "above-the-fold" content made available at visuallyLoaded.

performance.mark('fullyLoaded');
Emit this mark when your application has been completely loaded, for example any relevant "below-the-fold" functionality has been injected into the DOM, been marked visible, and is ready for user interaction. Any required startup background processing should be complete and should exist in a stable state barring any further user interaction.
]]
https://developer.mozilla.org/en-US/Apps/Build/Performance/Firefox_OS_app_responsiveness_guidelines#Implementation

**Comment by plehegar** [comment]
See also
 https://code.google.com/p/chromium/issues/detail?id=503661

**Comment by pmeenan** [comment]
On the Chrome side we are going to go ahead with implementing reporting for the 'navigationLoaded' mark and do some evangelism around it.  It's probably worth holding off on updating the spec until we see if there is uptake from developers and how useful it ends up being.

**Comment by eliperelman** [comment]
For what it's worth, the "time to critical content loaded" for Firefox OS is considered `visuallyLoaded`, since that is the core content on the page. `navigationLoaded` is for the UI content needed to navigate the site, like navigation bars, hamburger menus, etc.

**Comment by eliperelman** [comment]
For specifics on the usage of the recommended mark names adopted in Firefox OS, here are the references to the five marks within Gaia, the Firefox OS front-end:

https://github.com/mozilla-b2g/gaia/search?q=navigationLoaded+navigationInteractive+visuallyLoaded+contentInteractive+fullyLoaded&type=Code&utf8=%E2%9C%93

**Comment by igrigorik** [comment]
Closing this, the resolution was to drop recommended marks (see #9). If/when we can prove adoption of certain mark names we can revisit this discussion.
