### ISSUE TITLE
Use more appropriate error types

### ISSUE THREAD

**Issue by npm1** [w3c/user-timing#55]
@bzbarsky pointed out that SyntaxError is probably the wrong choice for some of the new errors introduced in User Timing L3, so we should change the error types.

**Comment by bzbarsky** [comment]
Fwiw, I suspect this ended up with SyntaxError because the L2 spec threw SyntaxError when passed a string that did not correspond to a mark name, and the same error type was used for all the new errors.  That usage of SyntaxError sorta kinda made sense, maybe, but th e new ones should be TypeError.

**Comment by annevk** [comment]
No, that also didn't make sense. SyntaxError should not be used.
