### ISSUE TITLE
StructuredDeserialize should be used; serialization records cannot be returned from IDL getters

### ISSUE THREAD

**Issue by jeremyroman** [w3c/user-timing#59]
The current draft specifies that the values should be serialized, but never deserializes them.

The output of `StructuredSerialize` (and its kin, like `StructuredSerializeForStorage`) isn't a cloned ECMAScript value, but a realm-independent serialization *record*. It can't be returned as the result of a getter, but needs to be passed to `StructuredDeserialize` at some point to return a new (cloned) ECMAScript value in the appropriate realm. (If that's always the realm that made it, you might even invoke it immediately.)

**Comment by npm1** [comment]
@wanderview FYI I plan to call `StructuredDeserialize` immediately on the output of `StructuredSerialize` as I think that achieves the cloning we intended.
