### ISSUE TITLE
Platform indicators

### ISSUE THREAD

**Issue by plehegar** [w3c/user-timing#6]
Performance markers, while they aren't specific from the spec that they
can't be used as platform indicators, are one of the closest things we have
to being able to use as an indicator. If they shouldn't be used as such,
that should probably more explicit, but having an API for indication would
be helpful. A use case I always come back to deals with painting: Why can't
a UA delay first paint until the application designates itself as visually
loaded? This would help avoid flashes of uninitialized content among other
things.

**Comment by igrigorik** [comment]
/cc @eliperelman @natduca 

FWIW, I don't think timing marks is the right approach to solve this. If we want to expose control over what holds painting, etc, then first we need to explain -- at the platform level -- which conditions hold rendering and why (lots of black magic here today), and then add appropriate hooks and APIs to control and override these behaviors.

**Comment by eliperelman** [comment]
I agree. Using user timing marks as platform hints is a smell of side effects. The connotation of `performance.mark` deals with specifying key points in lifecycle of a page, and is inherently time-based. I'm not sure what work has gone into "platform indicators", but having such an inversion of control for certain scenarios I think makes sense, but not by user timing. Maybe having something like `performance.indicate(FLAG, PAYLOAD)` is something that should be explored. Thoughts @igrigorik @natduca?

**Comment by igrigorik** [comment]
@eliperelman same issue, I think. If the intent is to indicate some notion of processing priority, then we should do that directly on the content (e.g. mark part of the tree as non-blocking/optional/whatever concept we need here)... instead of emitting a mark. The mark doesn't really tell us much in terms of helping optimize processing; it's only a thing that we know after we've done all the work.

**Comment by eliperelman** [comment]
Good point. Going back to the painting use case, it would be hard to know which apps want to block paint and which don't or don't have an implementation to block just by the use of a JavaScript API. Having a flag (in meta?) to define something may be needed. Just thinking out loud here.

**Comment by igrigorik** [comment]
@eliperelman I'll defer to @natduca on this one, he had previously floated some ideas around "optional elements". Related thread: https://lists.w3.org/Archives/Public/public-web-perf/2014Dec/0010.html

**Comment by igrigorik** [comment]
@eliperelman are you ok with resolving this discussion as a wontfix in context of user-timing? I think this well goes much deeper then that.. I think this is a discussion that ought to happen at "Houdini level".

**Comment by eliperelman** [comment]
@igrigorik yep! I think this is larger in scope than performance anyway, so good call.
