### ISSUE TITLE
Use WHATWG/INFRA 'is' definition for 'match'

### ISSUE THREAD

**Issue by himorin** [w3c/user-timing#80]
In step 2., spec states

> Otherwise, if mark is a DOMString, let end time be the value of the startTime attribute from the most recent occurrence of a PerformanceMark object in the performance entry buffer whose name matches the value of mark. If no matching entry is found, throw a SyntaxError.

which uses a text `whose name matches the value of mark` over user defined DOMString value. To use clear state, this text could refer [`is` in WHATWG/INFRA](https://infra.spec.whatwg.org/#string-is) instead of just `matches`. (also there is no clear definition of `match` in this spec.)

**Comment by npm1** [comment]
Sure, we can change `matches` to `is` (PR welcome, or I'll create one next week)
