### ISSUE TITLE
Undocumented exception in performance.measure()

### ISSUE THREAD

**Issue by hamishwillee** [w3c/user-timing#87]
Apparently there is an undocumented exception in performance.measure() if startMark or endMark name a mark that does not exist. This occurs in both chrome and firefox, and was raised in https://github.com/mdn/content/pull/11307

Ideally we'd document in MDN to reflect the spec - is this exception "unexpected" and if not, can you add information about it?

**Comment by npm1** [comment]
I think it is documented? See step 2 in https://w3c.github.io/user-timing/#dfn-convert-a-mark-to-a-timestamp. Otherwise, please provide an example to understand which one is not documented.

**Comment by hamishwillee** [comment]
Thanks @npm1 , I think you are right. Sorry for the time wasting.
