### ISSUE TITLE
It is unclear what "If startOrMeasureOptions is a non-empty PerformanceMeasureOptions object" means

### ISSUE THREAD

**Issue by smaug----** [w3c/user-timing#89]
What is a non-empty dictionary? (Maybe it is defined somewhere, but I couldn't find it. The spec links to map's definition of empty.)

**Comment by yoavweiss** [comment]
^^ @npm1

**Comment by yoavweiss** [comment]
I think it means 'If `startOrMeasureOptions` is a dictionary and contains at least one of "detail", "start", "duration" or "end"'.

**Comment by smaug----** [comment]
I think I can live with https://webidl.spec.whatwg.org/#es-dictionary . It is just unfortunate that it is not defined anywhere what an empty dictionary means.

**Comment by yoavweiss** [comment]
@smaug---- - Maybe the best path then is to file an issue against infra, defining an empty dict there and then we can point to that definition here?
