### ISSUE TITLE
Failed publishing

### ISSUE THREAD

**Issue by yoavweiss** [w3c/user-timing#96]
@caribouW3 - auto-publish gives the same [error](https://labs.w3.org/echidna/api/status?id=ac129737-89b1-457a-af61-7151b35e413d) as https://github.com/w3c/performance-timeline/issues/201
Can you take a look?

**Comment by marcoscaceres** [comment]
Hmm... I think it might a ReSpec bug and/or a regression (or recent change) in PubRules. I thought we were allowing the text to be "Commit History". 

@caribouW3, can you investigate and let me know. If it's a bug on ReSpec, please file an issue. All we need to change is:

https://github.com/w3c/respec/blob/9f803a8e5e673e740431f270953cfe074a5625cd/src/w3c/templates/headers.js#L235-L240

To use the URL instead.

**Comment by marcoscaceres** [comment]
I think it's working now thanks to https://github.com/w3c/user-timing/commit/efd1b58d9fb45b237992d62c032a87c70ff12a0e
